#!/bin/sh

find . ! -wholename '*/test/*' ! -wholename '*/lib/*' ! -wholename '*/_darcs/*' ! -wholename '*/drift_processed/*'  ! -wholename '*/regress/*'  \( -name '*.hs' -o -name '*.hsc' -o -name '*.m4' \) | xargs grep "$@" --
